# 工作流名称
name: Sync Image to Aliyun
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Ali DockerHub.

# 控制这个action什么时候运行
on:
  # 这里是只有master分支发生 push 或者 pull事件时才会触发action运行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Login to Ali Docker Hub
      env:
          # 目标仓库地址
          docker_repo: registry.cn-hangzhou.aliyuncs.com
          # 阿里云创建的命名空间
          ali_ns: docker-images-by-github
          # 指定镜像名称，此处，如果包含/，即多级目录；
          # 则target_image_name不能为空，并且必需重命名，而且不能包含多级路径
          image_name: bltavares/zerotier
          target_image_name: zerotier
          # 指定镜像标签
          tag: 1.14.0
          # 以下两个变量，不需要设置，临时使用
          s_tag: ""
          t_tag: ""
      run: |
          # 查看docker 版本
          docker version
          $s_tag: "$image_name:$tag"
          $t_tag: $docker_repo/$ali_ns/$image_name:$tag
          echo "拉取镜像：$s_tag"
          docker pull $s_tag
          echo "docker tag 转成 ali目标镜像"
          if ${{ contains(env.image_name, '/') }} ; then
            echo "镜像名，多级目录！！！"
            #docker tag $image_name:$tag $docker_repo/$ali_ns/$target_image_name:$tag 
            # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置，下面有介绍
            #docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} $docker_repo
            #echo "推送镜像到镜像仓库"
            # 推送镜像到镜像仓库
            #docker push $docker_repo/$ali_ns/$target_image_name:$tag
            t_tag: $docker_repo/$ali_ns/$target_image_name:$tag
          else
            echo "镜像名，非多级目录！！！"
            # docker tag 转成 ali目标镜像
            #docker tag $image_name:$tag $docker_repo/$ali_ns/$image_name:$tag 
            # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置，下面有介绍
            #docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} $docker_repo
            #echo "推送镜像到镜像仓库"
            # 推送镜像到镜像仓库
            #docker push $docker_repo/$ali_ns/$image_name:$tag
          fi
          echo "ali目标镜像：$t_tag"
