# 工作流名称
name: Sync Image to Aliyun
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Ali DockerHub.

# 控制这个action什么时候运行
on:
  # 这里是只有master分支发生 push 或者 pull事件时才会触发action运行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Ali Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      env:
          target_docker_repo: registry.cn-hangzhou.aliyuncs.com
          # 目标仓库：阿里云创建的命名空间
          ali_ns: docker-images-by-github
          # 指定镜像名称
          image_name: redis
          # 指定镜像标签
          tag: 7.4-rc
      run: |
          # 查看docker 版本
          docker version
          # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} $target_docker_repo
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag $target_docker_repo/$ali_ns/$image_name:$tag
          # 推送镜像到镜像仓库
          docker push $target_docker_repo/$ali_ns/$image_name:$tag
