# 工作流名称
name: Sync Image to Aliyun
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Ali DockerHub.

# 控制这个action什么时候运行
on:
  # 这里是只有master分支发生 push 或者 pull事件时才会触发action运行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    #- name: Git pull
    #  uses: actions/checkout@v3

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Ali Docker Hub
      env:
          # Ali Dcoker User
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # Ali Dcoker Pwd
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
          # 目标仓库地址
          docker_repo: registry.cn-hangzhou.aliyuncs.com
          # 阿里云创建的命名空间
          ali_ns: docker-images-by-github
          # 指定镜像名称
          image_name: redis
          # 指定镜像标签
          tag: 7.4-rc
      run: |
          # 查看docker 版本
          echo "1111"
          docker version
          echo "2222"
          echo "@@@@@@@:docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $docker_repo"
          # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置，下面有介绍
          docker login --username=ctu0307 --password=abcctu98760 $docker_repo
          echo "3333"
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag $docker_repo/$ali_ns/$image_name:$tag
          echo "444"
          # 推送镜像到镜像仓库
          docker push $docker_repo/$ali_ns/$image_name:$tag
